application: ron-private-mirror-service
version: 1
runtime: python
api_version: 1

handlers:

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /static/base(\.[0-9])\.css
  static_files: static/base.css
  upload: static/base\.css

- url: /static
  static_dir: static

- url: /admin
  login: admin
  script: mirror.py

- url: /cleanup
  login: admin
  script: mirror.py

- url: /kaboom
  login: admin
  script: mirror.py

- url: /main
  script: mirror.py
  secure: always

- url: /
  script: mirror.py
  secure: always

- url: /.*
  login: required
  script: mirror.py
  secure: always
